name = "proxy"
main = "src/index.js"
compatibility_date = "2024-05-23"
minify = true
account_id = "ea1aab81dc8e22018131832d124a54fc"
workers_dev = true

[[kv_namespaces]]
binding = "YUMI"
id = "8ff1913fa986482d967e0a5c7e2b0791"

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
